### ISSUE TITLE
script para descargar imágenes elecciones pasadas

### ISSUE THREAD

**Issue by str** [cancuengt/elecciones2015#1]
Desarrollar, probar y hacer commit del código para el script para descargar las imágenes

**Comment by str** [comment]
Falta cómo poder usarlo. Lo corro y no hace nada.

**Comment by cancuengt** [comment]
Hay usage en el script.
¿Qué falta? ¿Qué error te da?

Mario Soto
cancuen@gmail.con
..._

**Comment by str** [comment]
* Pone valores default si no definen el inicio y fin
* guardá las imágenes en una carpeta descriptiva  img/eleccion-1/  por ejemplo
* el parámetro está raro.. ¿cuando has visto que se definan los parámetros  -eleccion 1?  debería de ser --eleccion=1

**Comment by cancuengt** [comment]
1) La idea es que no definan valores por defecto, no todos van a descargar todas las mesas siempre, puede que si. Puedo extender las instrucciones en un archivo aparte si es necesario.
2) Esta es una buena idea, lo voy a hacer
3) Mirá el man page de find, alli lo he visto por ejemplo. Mirá los parámetros -ignore, -maxdepth, -atime, -ctime, etc.

**Comment by str** [comment]
1) OK, como querás.  Creo que es más fácil entender un programa que corre sin necesidad de ponerle parámetros. Creo que hace que más gente pueda correrlo y ver que hace, que correrlo y ver un mensaje y no hizo nada. Pero como querás está bien.

3) No estoy acostunmbrado a ver parámetros de de un solo guíón. El man de 'man'  por ejemplo tiene

-d, --debug
-l, --local-file
-w, --where

pero no tiene -where, -debug ni  -local fine. Lo mismo veo en el man de grep, ls, tar, bzip2, y los demás que uso más seguido. Pero como digo, si quitamos la necesidad de poner los params por default, creo que el problema sería menor.

**Comment by ykro** [comment]
No se si esto debe ir en issues separados o junto pero aquí van mis 5 pesos de opinión
-Aun que vamos a usarlo personas técnicas y sea un script más que un proyecto, creo que es importante tener un readme que indique qué hace el proyecto, la motivación, los pre-requisitos entre otros. Uso OS X y resulta que en Yosemite no hay wget, me di cuenta al ejecutarlo y ver miles de errores.

-También creo que es importante que se indique donde se guardan las descargas, cuál es el número inicial y cuál debería ser el número final, incluso si alguien quiere descargar todo que tenga una opción para eso

-Indicar que los límites son inclusivos, o sea que si pongo -inicio 1 -fin 2 va a descargar la 1 y la 2

-concuerdo con Stuardo que debería tener algún parámetro por defecto, incluso pueden ser que descargue una sola imagen y que el número sea aleatorio pero únicamente con ejecutar puedan tenerse datos

**Comment by str** [comment]
@ykro Ya hice la barrida de la descarga de las imágenes. Ya con las imágenes offline (12G) es más fácil pasarte copia que modificar el script para descarga.
