### ISSUE TITLE
tar.gz de las imágenes para descarga

### ISSUE THREAD

**Issue by str** [cancuengt/elecciones2015#2]
Ya una vez el robot corra para descargar tódas las ímagenes, empaquetarlas para descargar para pruebas

**Comment by cancuengt** [comment]
Probé bajando actas de 100 mesas, las 4 elecciones y pesa al rededor de 105 megas. Tomando en cuenta que son 16668 mesas estamos hablando que al menos va a tomar 17 Gigas. 
Por facilidad creo que va a ser mas fácil que se hagan archivos por lotes de mesas.
Sugiero hacer los grupos por cada 1000 mesas y una elección por cada grupo.
Esto porque no contamos con los rangos de mesas para cada municipio, pero si consiguiésemos esa información prefiero armar los grupos de esa forma.
¿Sugerencias?

**Comment by str** [comment]
OK, hice una barrida de todas las actas para la elección de presidente. Hay muchas mal escaneadas. Aproximadamente 350 actas están vacías. Todas las de presidente ocupan 4G. Traté de empacarlas todas y ocupan 3G.

Creo que si vamos a trabajar en conjuto, va a ser más fácil juntarnos y copiar todas por USB.
